//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WishList_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payments
    {
        public int Id { get; set; }
        public int WishId { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Amount { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Wishes Wishes { get; set; }
    }
}
